Document: airwave
Title: Debian airwave Manual
Author: <insert document author here>
Abstract: This manual describes what airwave is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/airwave/airwave.sgml.gz

Format: postscript
Files: /usr/share/doc/airwave/airwave.ps.gz

Format: text
Files: /usr/share/doc/airwave/airwave.text.gz

Format: HTML
Index: /usr/share/doc/airwave/html/index.html
Files: /usr/share/doc/airwave/html/*.html
